### ISSUE TITLE
registerRootAppElm should be called after launchApp() returns

### ISSUE THREAD

**Issue by liamzdenek** [KevinAst/feature-u#16] opened 2018-08-13 20:58 UTC
`registerRootAppElm` is called before launchApp() returns. The docs say to import `app` from the return value of launchApp() in order to access the publicFace[1]. This is problematic because React will attempt to render before app is defined, and will crash. I have personally encountered this by using mapStateToProps on a container which is rendered immediately (although not using feature-router).

A workaround exists by using setTimeout within registerRootAppElm:

```js
registerRootAppElm(rootAppElm) {
  setTimeout(() => {
    ReactDOM.render(rootAppElm, document.querySelector('#root'));
  }, 0);
}
```

[1] https://github.com/KevinAst/feature-u/blame/9e9fcd042a02a8734a389bf90a8a60a50d7737ac/docs/crossCommunication.md#L126

**Comment by KevinAst** [comment] 2018-08-15 12:06
Hello @liamzdenek,

Your post is very timely, as I have just released [feature-u V1], which indirectly addresses this very issue.

- **SideBar**: [feature-u V1] is a major new release that has redesigned how [Cross Feature Communication] is accomplished and includes cross-feature [UI Composition].  To get your arms around this, you really need to read through the [Cross Feature Communication] section.

  Upgrading to V1 requires some client code mods (see [V1 Migration Notes]), but it is well worth it.

  For the explanation that follows (to alleviate confusion), please note that what was called `app` is now `fassets` (feature assets).

I had already noticed this issue earlier.  Initially I had looked at several solutions:

 - Delaying react registration to the next event tick.  This is what you are currently doing in your work-around.

   Besides the fact that this seems like a bit of a hack, it unfortunately does not work on all all react platforms.  For example react-native/expo expects the the render process to occur synchronously (lest it errors).

 - Splitting up `launchApp()` into two processes, where a public `createFassets(features)` would emit the `fassets` object to be seeded into `launchApp()`.

   Unfortunately, this does not resolve the issue, it merely moves it to a different place.

As you have already highlighted, the crux of the problem is the heavy reliance that feature-u (pre V1) placed on importing `fassets`.  Because `fassets` is created/exposed by `launchApp()`, this resource is not available in a lot of startup scenarios.

[feature-u V1] has alleviated this issue (for components) by providing a [`withFassets()`] Higher-order Component (HoC) that auto-wires fasset resources into your component properties, using a [react context].  This is similar to how the popular redux `connect()` auto-wires state into your components.  This solution allows you to inject individual fasset resources into your components (through a mapping hook), or the entire fassets object itself (it's really a personal preference).  This is explained further here: [Inject fassets comp props].

While importing fassets is still available, it is used only as a last resort.

This new technique should alleviate the issue you are having where you need to delay react registration to the next event tick.

**Also**: In addition, V1 now passes `fassets` as a parameter to `registerRootAppElm()` _(if you care ... don't think this really impacts this discussion)_.

[Cross Feature Communication]:  https://feature-u.js.org/1.0.0/crossCommunication.html
[UI Composition]:               https://feature-u.js.org/1.0.0/crossCommunication.html#ui-composition
[Inject fassets comp props]:    https://feature-u.js.org/1.0.0/crossCommunication.html#inject-fassets-comp-props
[feature-u V1]:                 https://feature-u.js.org/1.0.0/history.html#v1_0_0
[V1 Migration Notes]:           https://feature-u.js.org/1.0.0/migration.1.0.0.html
[`withFassets()`]:              https://feature-u.js.org/cur/api.html#withFassets
[react context]:                https://reactjs.org/docs/context.html

**Comment by KevinAst** [comment] 2018-08-20 16:15
This issue has been resolved in the [feature-u V1] release using the [`withFassets()`] Higher-order Component (HoC).

Please refer to the explanation (above).

[feature-u V1]:                 https://feature-u.js.org/1.0.0/history.html#v1_0_0
[`withFassets()`]:              https://feature-u.js.org/cur/api.html#withFassets

**Closed by KevinAst** 2018-08-20 16:15 UTC
Labels: enhancement
